# YaHS Scaffolding Workflow Configuration

# Input files (required)
input:
  contigs: "/path/to/contigs.fa"           # Assembly contigs FASTA file
  
  # Hi-C reads - can specify single pair or multiple pairs
  # Single pair format (for backwards compatibility):
  # hic_r1: "/path/to/hic_R1.fastq.gz"
  # hic_r2: "/path/to/hic_R2.fastq.gz"
  
  # Multiple pairs format:
  hic_pairs:
    - r1: "/path/to/library1_R1.fastq.gz"
      r2: "/path/to/library1_R2.fastq.gz"
    - r1: "/path/to/library2_R1.fastq.gz"
      r2: "/path/to/library2_R2.fastq.gz"
    # Add more pairs as needed

# Output configuration
output:
  directory: "/path/to/output"             # Output directory
  prefix: "scaffolded"                     # Output files prefix

# Workflow parameters
parameters:
  threads: 16                              # Number of threads for BWA alignment
  java_memory: "32G"                       # Memory for Java applications
  sort_memory: "32G"                       # Memory for sorting during contact map generation

  # Duplicate marking method: 'biobambam2', 'picard', or 'sambamba'
  dedup_method: "biobambam2"

  # Generate BED file from BAM (optional)
  generate_bed: false

  # Contact map generation: 'juicer', 'pretext', or 'both'
  contact_map_method: "both"

  # Path to Juicer Tools JAR (if using juicer contact maps)
  juicer_tools_jar: "/usr/local/bin/juicer_tools.jar"

  # YaHS specific parameters
  yahs:
    # Resolution series (comma-separated, e.g., "1000,5000,10000")
    # resolution: "1000,5000,10000"

    # Start from existing AGP file
    # agp_file: "/path/to/existing.agp"

    # Skip error correction rounds
    no_contig_ec: false
    no_scaffold_ec: false

    # Restriction enzyme motifs (e.g., "GATC,GANTC")
    # enzyme_motifs: "GATC"

# Logging configuration
logging:
  level: "DEBUG"                           # DEBUG, INFO, WARNING, ERROR (DEBUG for troubleshooting)
  file: "yahs_workflow.log"                # Log file name

# Example advanced configuration:
# parameters:
#   threads: 32
#   java_memory: "64G"
#   dedup_method: "sambamba"
#   generate_bed: true
#   contact_map_method: "both"
#   yahs:
#     resolution: "1000,2000,5000,10000,20000,50000"
#     enzyme_motifs: "GATC,GANTC"
#     no_contig_ec: false
#     no_scaffold_ec: false
