# YaHS Scaffolding Workflow Configuration

# Input files (required)
input:
  contigs: "/home/petr/PycharmProjects/yahs_pipeline/test_data/dm3.fasta"           # Assembly contigs FASTA file
  hic_r1: "/home/petr/PycharmProjects/yahs_pipeline/test_data/HiC_S2_1p_10min_lowU_R1.fastq.gz"      # Hi-C reads forward
  hic_r2: "/home/petr/PycharmProjects/yahs_pipeline/test_data/HiC_S2_1p_10min_lowU_R2.fastq.gz"      # Hi-C reads reverse

# Output configuration
output:
  directory: "/home/petr/PycharmProjects/yahs_pipeline/tmp"             # Output directory
  prefix: "scaffolded"                     # Output files prefix

# Workflow parameters
parameters:
  threads: 6                              # Number of threads for BWA alignment
  java_memory: "32G"                       # Memory for Java applications

  # Alignment method: 'default' (standard BWA) or 'omnic' (Omni-C pairtools workflow)
  alignment_method: "default"
  
  # Duplicate marking method: 'biobambam2' or 'picard'
  dedup_method: "biobambam2"

  # Generate BED file from BAM (optional)
  generate_bed: false

  # Generate manual curation files for Juicebox
  generate_manual_curation: true

  # Path to Juicer Tools JAR (if using juicer contact maps)
  juicer_tools_jar: "/usr/local/bin/juicer_tools.jar"

  # YaHS specific parameters
  yahs:
    # Resolution series (comma-separated, e.g., "1000,5000,10000")
    # resolution: "1000,5000,10000"

    # Start from existing AGP file
    # agp_file: "/path/to/existing.agp"

    # Skip error correction rounds
    no_contig_ec: true
    no_scaffold_ec: true

    # Restriction enzyme motifs (e.g., "GATC,GANTC")
    # enzyme_motifs: "GATC"

# Logging configuration
logging:
  level: "INFO"                            # DEBUG, INFO, WARNING, ERROR
  file: "yahs_workflow.log"                # Log file name

# Example advanced configuration:
# parameters:
#   threads: 32
#   java_memory: "64G"
#   dedup_method: "picard"
#   generate_bed: true
#   generate_manual_curation: true
#   yahs:
#     resolution: "1000,2000,5000,10000,20000,50000"
#     enzyme_motifs: "GATC,GANTC"
#     no_contig_ec: false
#     no_scaffold_ec: false
